awesome-gptX/awesome-gpt

- README.md
The projects are python based projects with chatgpt which automates with third-party extensions, integrations with other tools, ports for different platforms, etc. That repository is also under development and new features will keep getting added. Thank you!
> Added a few resources under `ChatGPT Integrated Projects`

- README.md
Added Chrome extension: ChatGPT for Twitter
Added Webapp: Epic Music Quiz
> Added ChatGPT for Twitter and EpicMusicQuiz

- README.md
[PromptSandbox.io](promptsandbox.io) is a free and easy-to-use node-based visual programming web application to help create automated workflows that uses OpenAI APIs.
- Added Promptsandbox in the Web Applications section
Thank you 🙏
> add promptsandbox.io

- README.md
> Add HappyCommit

- README.md
Add Poet.ly as web application
> Add Poet.ly

- README.md
It is also a userscript (can click 'Get on Greasy Fork')
> Added ChatGPT Widescreen Mode to userscripts

- README.md
Add chatgpt-create-unit-tests GitHub Action
> Add chatgpt-create-unit-tests GitHub Action

- README.md
Add a link to Code ChatGPT Plugin
> Add a link to Code ChatGPT Plugin

- README.md
I like to suggest this simple bookmarklet that can be used in different browser to export chats.
> Add ChatGPT Export bookmarklet link

- README.md
Hi!
I believe this library would be a great additon
> Add openai-functools, a library for simplifying management and creation of openai functions metadata

- README.md
gpt-json is a library that enables interaction with OpenAI's GPT models using JSON and supports schema validation with yup.
Please let me know if you need more information.
> Adding gpt-json

- README.md
- README.star.md
- README.zh-cn.md
- README.zh-cn.star.md
Updating API Tools with a trending tool
Embedchain - 3.9K stars
It helps create ChatGPT like bots with only a few lines of Code.
Repo Link: https://github.com/embedchain/embedchain
> update: API tools with embedchain

- README.md
- README.star.md
- README.zh-cn.md
- README.zh-cn.star.md
Hi, This is a fun learning app I made, hope it will be added to the list
> update: Web Application with examor

- README.md
- README.zh-cn.md
We, the DEEPNIGHT Team are adding our **aiforcause** resource pack to the list.
We are providing GPT-3.5-16k + Function calling free-to-use to all.
We will add more APIs and resources to it soon.
> Adding DEEPNIGHT aiforcause API

- README.md
I'm from the team at Wielded. We are constantly adding new features to the application and are committed to making individual access free for the community. 
An upcoming feature is allowing users to generate prompts for their task!
> Adding Wielded

- README.md
Hi @edison1105, I added BrainSoup, a native multi-LLM client for Windows with advanced features such as local document indexing, RAG, multi-modality, multi-agent automation, code interpreter, sandboxed file system and the ability for agents to interact with the local system via customizable events and tools. More information can be found [here](https://www.nurgo-software.com/products/brainsoup).
I kindly ask for your review of this PR. Thanks for creating this awesome list!
> Add BrainSoup to desktop applications list

- README.md
Hi!
The Composum AI provides extensions for both the Adobe Experience Manager (AEM) or the free Composum Pages CMS that
tightly integrates OpenAI ChatGPT capabilities into the CMS editor to allow content authors to analyze and discuss 
content with ChatGPT, suggest completions, translate, transform texts, and more. It also allows free prompting of 
ChatGPT. Hopefully that fits into your list!
Github: https://github.com/ist-dresden/composum-AI
Site: https://ist-dresden.github.io/composum-AI/
Quick Demo: https://www.youtube.com/watch?v=lSdKlwIDPkE / https://www.youtube.com/watch?v=96gv-F4zX_o
Language: Java
Licence: MIT licence
> Add Composum AI CMS extension

- README.md
The AI based code generation pipeline provides a way to generate code or text from source files and prompt files so that
the output is only regenerated when the input(s) have changed. Thus it is suitable for code generation in projects -
this saves time e.g. if used in a build process and there is no need to check the (normally checked in) generation 
result again until that is really needed.
There is a command line tool and a small Java framework if many files need to be checked / generated.
Github: https://github.com/stoerr/AIGenPipeline
Site: https://aigenpipeline.stoerr.net/
Language: Java
Licence: Apache-2.0
> add ai code generation pipeline

- README.md
I added a website that allows you to build chatbots (Zapier) to the web applications. I personally found it to be very useful.
> Addition to web applications

- README.md
- README.star.md
- README.zh-cn.md
- README.zh-cn.star.md
It is like my other chatbots on this list but for Amazon.com and its international versions, integrates as collapsible chatbot in bottom-right corner of site
> Add AmazonGPT to Chat bots + User Scripts

- README.md
- README.zh-cn.md
[Docky AI](https://docky.ai/) is a powerful browser extension that allows you to have real-time conversations with multiple AI models through a sidebar. It supports simultaneous communication with multiple models and can assist you in reading web pages, writing, translating, and creating images
> add Docky AI

- README.md
- README.zh-cn.md
Casibase provides an open source LangChain-like AI knowledge database and chatbot built using Golang with Admin UI and multi-model support (DeepSeek R1, ChatGPT, Claude, Llama 3, HuggingFace, etc.). Capable of delivering AI-driven smart replies.
github: https://github.com/casibase/casibase
docs: https://casibase.org/
> add Casibase
